### ISSUE TITLE
Level:RemoveCurse( LevelCurse Curse ) Seemingly No Longer Exists?

### ISSUE THREAD

**Issue by skykittenpuppy** [epfly6/RepentanceAPIIssueTracker#138]
![image](https://user-images.githubusercontent.com/77988291/118567226-4f055580-b76d-11eb-8130-112820c4fadd.png)

![image](https://user-images.githubusercontent.com/77988291/118567137-2aa97900-b76d-11eb-8ab8-1faebf9bbe7a.png)

**Comment by epfly6** [comment]
It's deprecated method. Use RemoveCurses instead https://wofsauge.github.io/IsaacDocs/rep/Level.html?#removecurses
(Yeah, it's a very good idea to respond after two years, but ugh, close this issue)
